version: '3.5'

services:
  emuat_db:
    build: .
    image: emucat_db
    container_name: emucat_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - <local dir>:/var/lib/postgresql/data
    networks:
      - emucat_network

networks:
  emucat_network:
    name: emucat_network
    driver: bridge