version: '3.5'

services:

  emucat_vo:
    image: emucat_vo
    container_name: emucat_vo
    build:
      context: .
      dockerfile: Dockerfile.vo
    ports:
      - 8080:8080
    networks:
      - emucat_network

networks:
  emucat_network:
    name: emucat_network
    driver: bridge

volumes:
  static_volume:  # <-- declare the static volume
  media_volume:  # <-- declare the media volume